### PR TITLE
Update electron

### PR DESCRIPTION
**Pull request by Pukimaa**
Please just do it....If there are any breaking changes you still need to change discord's source code ofc. Just focus on that for a moment and everyone will love you.

EDIT: As of the 11th of February 2023, Discord Canary switched to Electron 22. This is a great step. Also for those who complained about this PR...it should be more of a heads up to the Discord Team and not an actual thing that should be merged.

### CODE REVIEW

**Comment by koyuawsmbrtn** [comment]
pls discord give us xdg-desktop-portal uwu

**Comment by ItsCryptic** [comment]
yes, please do this discord!

**Comment by ItsCryptic** [comment]
https://support.discord.com/hc/en-us/community/posts/6935988701335-Update-Electron- upvote this!!

**Comment by orowith2os** [comment]
Please, Discord. Fix your client. Just merge, and work out the major bugs. This is all you need for your software to work on the Deck, on Linux, and securely on Windows and macOS. Everybody has been asking for this for years now. Barely a month, at least, just give this pull request some attention and see if you can get it functioning. You're a multibillion-dollar company, you can afford to put some effort towards this.

**Comment by KaspianDev** [comment]
Hell yea

**Comment by KaspianDev** [comment]
I don't think they care at all. At the end of the day it's their job to keep their proprietary app up to date.

**Comment by DaRacci** [comment]
For all that is holy please for the love of god merge this

**Comment by sadmuphin** [comment]
Please discord we're begging you 🙏 

I'll sub to nitro for a year just merge this

**Comment by sonphantrung** [comment]
Dang, doubt the author is active: there are merge conflicts

**Comment by ToothyDev** [comment]
Please, the RAM leaks are getting insane. I have to restart Discord a couple of times a day because it eats up to 2GB of RAM

**Comment by ItsCryptic** [comment]
The latest Discord canary build updates electron to 17!!

**Comment by ItsCryptic** [comment]
image

**Comment by ryleu** [comment]
can confirm canary is updated to electron 17, but screen sharing and portals are still broken. this is a step in the right direction, but they've got to use the new electron APIs for it to make a difference

**Comment by ryleu** [comment]
looks like we've got a merge conflict, might work on that if i have free time... don't wait on me though

**Comment by Pukimaa** [comment]
> looks like we've got a merge conflict, might work on that if i have free time... don't wait on me though

Yeah that's more a problem with them changing some stuff so it works with Discord. They would have to resolve those etc. But will take maximum a month if they're listening

**Comment by Slimemaster0** [comment]
Discord does work with vanilla electron19, as proven by this aur package: [https://aur.archlinux.org/packages/discord-electron-bin](https://aur.archlinux.org/packages/discord-electron-bin)

**Comment by halamix2** [comment]
Realistically speaking, how feasible it would be to check on which commit Discord Electron is based on, listing all changes, and creating a PR from relatively fresh Electron fork that would take into consideration Discord's Electron custom bits and pieces?
Would there be any incompatibilities with React/other components?

**Comment by halamix2** [comment]
I see the issue with this PR would be that the Discord's `main` branch is not updated, mostly `17-x-y` is updated, so the better solution would be to create `23-x-y` branch in this repo ([or for any supported version of electron](https://endoflife.date/electron)), but this cannot be done from a PR level, it has to be done by a repo administrator.
Hopefully that kind of bump would fix issue with audio streaming on Linux

**Comment by KaspianDev** [comment]
It's fucking pointless at this point lmao. Use your time on a project that is worth it 😉.

**Comment by PlatinumLucario** [comment]
I can confirm that by forcing latest Discord Canary (at the time of this writing) into using native Wayland, it runs natively in Wayland, but there's a catch:

No window management has been added into its code. This window management code is required for every Wayland application to avoid the application becoming a windowless application, in other words, it cannot be resized or moved around on the display, but can be put into full screen.

I haven't tested window capture feature in screen sharing yet, but I will update this message when I do.

**Comment by orowith2os** [comment]
Latest Discord stable is using Electron 22!

Native Wayland works, but it still uses the old Discord menus for screenshare; force enabling it causes a segfault. Progress, though! 

`com.discordapp.Discord --enable-features=UseOzonePlatform,WaylandWindowDecorations,WebRTCPipeWireCapturer --ozone-platform=wayland`

**Comment by felipec** [comment]
Discords is always 1 hour off in Mexico. Apparently this is fixed in electron 24.0.0.

Please do this.

**Pull request closed without merging**
